### ISSUE TITLE
Need to check - the jobs error codes

### ISSUE THREAD

**Issue by gecube** [eftechcombr/glpi#62]
Hi!

I am confused and feel like if Jobs are failing, the exit codes are successful, so k8s won't restart them.

Proofs:

<img width="1217" alt="Screenshot 2024-04-23 at 15 53 39" src="https://github.com/eftechcombr/glpi/assets/2912732/64793ac5-85ee-43bb-8b57-14a47c204bdc">
<img width="1219" alt="Screenshot 2024-04-23 at 15 53 34" src="https://github.com/eftechcombr/glpi/assets/2912732/140ef824-d1b1-4bdc-8659-fcf5c00d9846">
<img width="1211" alt="Screenshot 2024-04-23 at 15 53 26" src="https://github.com/eftechcombr/glpi/assets/2912732/7040334c-266a-426c-93eb-d4f69f5fc5e0">
<img width="1216" alt="Screenshot 2024-04-23 at 15 53 21" src="https://github.com/eftechcombr/glpi/assets/2912732/a08cb1d7-bce4-443a-a49a-70a1ec16d539">

Need to double check that if something is wrong, Jobs will exit with the proper exit code (!=0).

**Comment by eduardofraga** [comment]
Fixed, please remove and create the Job again because are imutables. 

[kubernetes/mariadb-job.yaml](https://github.com/eftechcombr/glpi/blob/75-permission-issue/kubernetes/mariadb-job.yaml)

```
      restartPolicy: OnFailure
  parallelism: 1
  completions: 1
````
