### ISSUE TITLE
Permission Issue

### ISSUE THREAD

**Issue by HelbertLopez** [eftechcombr/glpi#75]
I'm having an issue with permission on the deployment 

![image](https://github.com/user-attachments/assets/798c0360-c802-489e-a156-bb634fe71609)

 Im think im missing something.

Another thing I'm want to confirm : Is glpi-job use on upgrade or either on the first deployment?

**Comment by eduardofraga** [comment]
Try delete and create the job [glpi-verify-dir](https://github.com/eftechcombr/glpi/blob/latest/kubernetes/glpi-job.yaml#L5C24-L5C24)

**Comment by eduardofraga** [comment]
Fixed, remove and create jobs again because Jobs are imutables.  

```
      restartPolicy: OnFailure
  parallelism: 1
  completions: 1
```
